input {
  beats {
    port => 5044
  }
}

filter {
  if [container] and [container][name] {
    mutate {
      add_field => { "service" => "%{[container][name]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dynamic-pricing-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
